# Generated by Django 2.2.6 on 2020-04-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentcode', models.TextField()),
                ('adminno', models.TextField()),
                ('studentname', models.TextField()),
                ('classname', models.TextField()),
                ('section', models.TextField()),
                ('dob', models.TextField()),
                ('result', models.TextField()),
            ],
        ),
    ]
