# Generated by Django 2.2.6 on 2020-04-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200410_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentcode', models.TextField()),
                ('adminno', models.TextField()),
                ('studentname', models.TextField()),
                ('slassname', models.TextField()),
                ('section', models.TextField()),
                ('dob', models.TextField()),
                ('result', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='loginn',
        ),
    ]
