# Generated by Django 2.2.6 on 2020-04-10 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200410_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='slassname',
            new_name='classname',
        ),
    ]
